# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('didData', '0004_auto_20160722_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediainactividad',
            name='imagen',
            field=models.CharField(max_length=200),
        ),
    ]
