# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 16:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('didData', '0006_slider_sliderdet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='idActividad',
        ),
        migrations.RemoveField(
            model_name='sliderdet',
            name='idSlider',
        ),
        migrations.DeleteModel(
            name='Slider',
        ),
        migrations.DeleteModel(
            name='SliderDet',
        ),
    ]
