# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('didData', '0007_auto_20160726_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actividaddet',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mediainactividad',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actividad',
            name='identificacion',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='actividaddet',
            name='identificacion',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mediainactividad',
            name='identificacion',
            field=models.IntegerField(),
        ),
    ]
