# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('didData', '0009_slider_sliderdet'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediainactividad',
            name='idTema',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='didData.Tema'),
            preserve_default=False,
        ),
    ]
